### ISSUE TITLE
Survive the death of Structurizr Express

### ISSUE THREAD

**Issue by aviflax** [FundingCircle/fc4-framework#284]
As announced in #268.

This is a goal + plan ticket.

## The Plan

* [ ] Add background/context/introduction to this ticket.
* [ ] Design and implement a new C4 YAML DSL that decouples models and views, as per [Enhancement Proposal EP01: Decoupling Models and Views with a New DSL](https://github.com/FundingCircle/fc4-framework/blob/b3b7203/docs/archive/proposals/ep01-decouple-models-and-views-new-dsl/ep01-decouple-models-and-views-new-dsl.md)
  * [x] Design the new model DSL and create schemata for it » #231
  * [ ] Add a new validation flag to the CLI that will validate models » #272 (in progress)
  * [ ] Design the new view DSL and create schemata for it » (ticket coming soon)
  * [ ] Extend the CLI’s validation feature to validate views as well » (ticket coming soon)
* [ ] Implement a new renderer » #5 (in progress)
* [ ] Make the new renderer invocable via the CLI » (ticket coming soon)
* [ ] Comprehensively review and revise the docs » (ticket coming soon)

**Comment by aviflax** [comment]
I think I’ve run out of time to implement this plan as-is before the deadline, which is in 3 weeks. So for now, as a stopgap, I’ll try #288.
