### ISSUE TITLE
Rename FC4C to fc4-tool and host it and the framework in the same repo

### ISSUE THREAD

**Issue by aviflax** [FundingCircle/fc4-framework#58]
The current name is awful. It’s confusing and especially hard to use verbally. I was in a workshop with n00bs, and trying to talk about FC4 vs FC4C… well, it was a disaster.

It’s also annoying and unnecessary to juggle/jump between the two repos.

This will make documentation, examples, etc much better+easier.

And we’ll be able to make atomic changes to the tool and the methodology rather than having to coordinate changes across two repos.

(This is tracked as ENG-1479 and ENG-1656 in Funding Circle’s internal issue tracker.)

### Tasks

- [x] Merge all commits from the fc4-framework repo into this repo (#59, #60, #61)
- [x] Clone both open issues from that repo to this one
- [x] Delete that repo
- [x] Rename this repo to fc4-framework
- [x] Enable GitHub Pages for this repo and make whatever tweaks are necessary to re-publish the framework site at [the same URL](https://fundingcircle.github.io/fc4-framework/) it’s currently using

**Comment by aviflax** [comment]
My current thinking on how I’ll approach this:

1. Merge all commits from the `fc4-framework` repo into this repo
1. Clone both open issues from that repo to this one
1. Delete that repo
1. Rename this repo to `fc4-framework`
1. Enable GitHub Pages for this repo and make whatever tweaks are necessary to re-publish the framework site at [the same URL](https://fundingcircle.github.io/fc4-framework/] it’s currently using

The reasoning:

* One of the repos will naturally need to be deleted, but I’d like to break as few links and lose as little data as possible.
* There are various kind of links:
  * Many commits reference pull requests and issues via GitHub’s `#XX` syntax
     * Especially merge commits; almost all reference their PR
  * External links to the GitHub Pages site for the framework: https://fundingcircle.github.io/fc4-framework/
* In terms of data, commits are fairly easy to migrate. But issues and PRs, not quite so easy.
  * In fact I think the only way to migrate PRs would be to get assistance from GitHub’s customer service department. Which we could do, but might be a pain.
  * Issues can be migrated by essentially cloning them from one repo to another. They end up with a different ID number and URL, but would have the same contents, labels, etc. (This could be done manually for a very small set of issues; for a larger set I’m sure we could find a script somewhere.)
* The `fc4c` repo has way more issues and PRs than the `fc4-framework` repo

**Comment by aviflax** [comment]
TIL that when you rename a repo GitHub sets up redirects from the old name to the new name. Very nice!

**Comment by aviflax** [comment]
Done!
